export const FETCH_JOBS = 'FETCH_JOBS';
export const FETCH_SINGLE_JOB_SKILLS = 'FETCH_SINGLE_JOB_SKILLS';
export const FETCH_SINGLE_SKILL_JOBS = 'FETCH_SINGLE_SKILL_JOBS';
export const FETCH_SEARCH_JOBS = 'FETCH_SEARCH_JOBS';
